### ISSUE TITLE
When loading a .prg it automatically attaches the ",1" even without using the switch

### ISSUE THREAD

**Issue by adtbm** [MEGA65/m65connect#1]
when loading a program, m65 automatically loads it as per "foo",8,1 instead of "foo",8

it only should load ,8,1 when the function "-1" is attacxhed to the m65 command

**Comment by gardners** [comment]
Fixed in mega65-tools. Just incorporate latest m65 binaries to resolve.

**Comment by Taygair** [comment]
Should be fixed with latest implementation of m65
