### ISSUE TITLE
M65Connect console cannot send an empty line?

### ISSUE THREAD

**Issue by dansanderson** [MEGA65/m65connect#10]
As far as I can tell, the M65Connect console cannot send an empty line (a carriage return without text). As far as I can tell, a return on an empty line is the only way to step the CPU in trace t1 mode. If I'm wrong on either of these, please correct me. Otherwise, consider a feature request that pressing Enter while the text field has focus but is empty should send a carriage return character and print responses.

M65Connect version 2.0, Mac.

**Comment by Taygair** [comment]
Just tested, must have been fixed in a previous version.
