### ISSUE TITLE
File Path settings: save disabled

### ISSUE THREAD

**Issue by CLU4983** [MEGA65/m65connect#13]
Save button is disabled in File path settings dialog.
"Path Vivado" shows "Searching ..." and buttons on the right side are disabled, too ("Choose folder ..." and "Start searching").
Therefore file path settings cannot be saved and have to be choosen again at every new start of the program.

**Comment by Taygair** [comment]
I need to easen the process here. As long as the search for Vivado is not complete M65Connect start searching again on next start. While this search is going on (and that can be very long depending on size/file amount of HDs) the save option is blocked. 
I guess it's the easiest I simply remove the auto search on startup and let the user set the path to vivvado.bat

**Comment by Taygair** [comment]
Removed auto-search in V2.2 The auto-search caused more problems than it was helpful You now simply can select the path to vivado.bat or Vivado-lab.bat manually.
