### ISSUE TITLE
Saving a screenshot as a replacement should not be a fatal error

### ISSUE THREAD

**Issue by dansanderson** [MEGA65/m65connect#14]
M65Connect 2.1, macOS Ventura (updated version). I tried to save a screenshot using the name of an existing file. The macOS file picker correctly confirmed that I wanted to replace the existing file (I did), but then M65Connect was so opposed to the idea that it shut itself down with this pop-up message:

![CleanShot 2022-12-22 at 22 42 09](https://user-images.githubusercontent.com/408973/209285701-72b78472-e96f-4fd8-b3cd-45db9f22e11a.png)

I don't know what this case looks like on other OSes, but at least with the macOS file picker I had the opportunity to confirm that I wanted to replace the existing file. Ideally, M65Connect would simply proceed to replace the file.

**Comment by Taygair** [comment]
Great finding! It looks like the Replace warning is coming from the "Save as" dialog but it doesn't care of replacement itself. :( Will be fixed in M65Connect V2.2
