### ISSUE TITLE
Remember last selected directory paths in file picker dialogs

### ISSUE THREAD

**Issue by dansanderson** [MEGA65/m65connect#15]
Feature request: I'd like file picker dialogs to remember the last selected directory path. For example, if I'm taking multiple screenshots and want them all saved to my Desktop folder, I need to navigate to the Desktop folder each time. I'd like to navigate to the Desktop folder the first time, and have it selected automatically for the next screenshot.

I think it's probably fine and expected to have a single global "current" directory for all file dialogs. It's OK if I save a screenshot to the Desktop then try to send a PRG and it opens the file picker to the Desktop. Maybe an OS style guide has a different opinion, but this seems to be the behavior of other apps.

**Comment by Taygair** [comment]
Uff, there are many file selections within M65Connect. Have to think about it in what way it makes sense to implement them (all).

**Comment by Taygair** [comment]
I was thinking a bit longer about your issue. This is not the first issue of that type. Anton initially wanted me to allow different directories depending on file types. The solution for this can be found at menu File Paths. This allows you to set specific parts for different file types (Anton did a lot of tests at that time and was happy to differ directories based on file types). So it's a more detailed solution than you are asking for (in your case you would set paths the same). 
The PRG path you mention is listed but the screenshot path is not listed there and I could add it. If you have issues with any other missing file paths please let me know. 
Regarding default path for screenshots: If I got you right you want to have the default path set when you open the "Save as..." window in the Screenshot window?

**Comment by dansanderson** [comment]
My expectation from other apps is that the app starts with a sensible default, then when I navigate to another directory to save a file, it remembers that directory as the starting point for the next attempt. This handles the use case where I'm performing the action repeatedly.

My first guess is that there should just be one current working directory for the entire app, and it's always the last-used directory, regardless of task or file type. I could be wrong, maybe it'd be useful to track separate working directories by task or type, I just can't think of an app that does it that way. (Fancy apps like IDEs do this with a "workspace" metaphor, which it probably overkill for M65Connect.)

**Comment by Taygair** [comment]
As mentioned, for testers (and others) it might be useful to have different default directories. I don't know who all is currently using it but it, try to avoid a sh... storm that way. So by what you are saying in regard what is currently there:
- Allow to set a default directory that is used in all load/save file dialogues
- The default directory can be "overwritten" by
     a) first order: the previous selected file path while load/save a file (this might annoy users wanting the default dir always, dunno)
     b) second order: Specific filetype directory (menu File Paths) **if set**

I see what you want but don't but I don't want to break the current implementation (that already might be used by users), just trying to find a way that makes you happy in this regard without changing everything here.

**Comment by dansanderson** [comment]
Honestly I completely forgot File Paths existed. I'd consider that sufficient if you'd prefer to close the issue. It's not standard but it has its own advantages.

Thanks for considering it!

**Comment by Taygair** [comment]
Let's see what the "survey" in DC will show up. Maybe any major changes won't happened for upcoming release but then the one after. A quick solution for upcoming release might be to add Screenshot default path in menu File Paths.

**Comment by Taygair** [comment]
I pretty much implemented it the way you described in version 2.2
