### ISSUE TITLE
Copy files directly to floppy

### ISSUE THREAD

**Issue by MauriceMEGA65** [MEGA65/m65connect#17]
Not an issue, but feature request: ability to copy D81 images from pc directly to a floppy in the internal floppy drive of the MEGA65.
Currently we have the button “SD Card”, I was hoping to see a “Floppy” button next to it.

**Comment by Taygair** [comment]
Yes, that is a nice feature but keep in mind that M65Connect is just a wrapper of all the cli tools and can't do much more than what the cli tools (m65, mega65_ftp, ...) are offering. Direct access is currently not supported that way.

**Comment by Taygair** [comment]
Will close this ticket as it's not controllable by M65Connect.  Needs to be directed to https://github.com/MEGA65/mega65-tools
