### ISSUE TITLE
Feature request: able to copy MOD files

### ISSUE THREAD

**Issue by MauriceMEGA65** [MEGA65/m65connect#19]
.MOD files are currently not supported by M65Connect, so copy files to SD is only possible by taking out SD card and inserting it in a PC.
Please make .MOD part of the supported file types.

**Comment by Taygair** [comment]
For next release I completely remove any copy file restriction by extenstion (except D81 image).

**Comment by Taygair** [comment]
File extension restriction removed with version 2.2
