### ISSUE TITLE
sending PRGs bigger then 20KB fails on Windows

### ISSUE THREAD

**Issue by adtbm** [MEGA65/m65connect#2]
when i send a program via >m65 -F -4 -r foo.prg< and the file is bigger than 20KB
m65 fails to send it. the terminal in Windows gets flooded with:
Failed to write all bytes to port: The operation completed successfully.
Failed to write all bytes to port: The operation completed successfully.
Failed to write all bytes to port: The operation completed successfully.
Failed to write all bytes to port: The operation completed successfully.
Failed to write all bytes to port: The operation completed successfully.
Failed to write all bytes to port: The operation completed successfully.
...

only way to stop this is by pressing CTRL & C

MEGA65 looks always, regardless of which PRG i try to load, like this:

![2020-05-25 22 53 20](https://user-images.githubusercontent.com/35996116/82844684-b3d2fa80-9ee1-11ea-84cf-fdccd73dffe0.jpg)

**Comment by gardners** [comment]
Fixed in mega65-tools. Just incorporate latest m65 binaries to resolve.

**Comment by Taygair** [comment]
Latest CLI tools implemented in M65Connect, fixed.
