### ISSUE TITLE
M65Connect doesn't startup on Arch Linux

### ISSUE THREAD

**Issue by nils-eilers** [MEGA65/m65connect#8]
It just gives an error message "An exception of class NilObjectException was not handled. The application must shut down."

Any suggestions?

**Comment by Taygair** [comment]
In general M65Connect is tested on Ubuntu. Make sure to consider this:

You need to be in the groups 'dialout' and 'plugdev':
1. Start Linux and open a Terminal window
2. Add your user to this group by typing: sudo usermod -a -G dialout,plugdev <username>
    while <username> represents your Linux user name. You can use $USER for the active user.
3. You NEED to restart Linux to take effect of these changes!

Furthermore I'd like to know if the error message comes on starting M65Connect or later?
Already tried to start M65Connect with sudo?

**Comment by Taygair** [comment]
Not sure if you made it working in between. M65Connect on Linux is Intel only atm. With latest release the framework also supports AMD64 which I have to test first.

**Comment by nils-eilers** [comment]
Sorry, I should have provided some feedback. Yes, I've been able to start M65Connect meanwhile. I switched to Manjaro Linux  (which is Arch based so it isn't completely different) and it starts up without further hassle. However I had some trouble with a couple of programs, which turned out to be caused by a certain version of the boost library. These programs would then start with passing the evironment variable LANG=C, not sure if M65Connect was also one of these programs.

**Comment by Taygair** [comment]
Glad to hear! I'm really no Linux guy and I know there are many derivates around. M65Connect 2.1 with refactored CLI tools will be published soon. Maybe they also improve stability on your side then too. Afaik they are also static, so no other libs from OS required.
